repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        args: [--target-version, py312, --preview, --enable-unstable-feature=string_processing]
        language_version: python3.12
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.7"
    hooks:
      - id: ruff
        language_version: python3.12
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath
          - license_header.txt
          - --comment-style
          - "\"\"\"||\"\"\""
          - --allow-past-years
          - --use-current-year
          - --no-space-in-comment-prefix

ci:
  autofix_commit_msg: "ci: auto fixes from pre-commit.com hooks"
  autoupdate_branch: "main"
  autoupdate_commit_msg: "ci: pre-commit autoupdate"
